# === BANCO DE DADOS DO RENDER (Pausado) ===
#spring.datasource.url=jdbc:postgresql://dpg-d814e3naqgkc73algps0-a.ohio-postgres.render.com/mapa_db_77ly
#spring.datasource.username=mapa_db_77ly_user
#spring.datasource.password=G5xUsIdvbNnJr6OjuHzGwZgwIdeqb2qc

# O Spring vai tentar criar as tabelas automaticamente se elas não existirem
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === NOVO BANCO DE DADOS GRÁTIS (Neon.tech) ===
spring.datasource.url=jdbc:postgresql://ep-lucky-hat-acl5ozmt-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_NmvJEx94bQSC



# O Spring vai tentar criar as tabelas automaticamente se elas não existirem
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect