# URL do banco (Externa)
spring.datasource.url=jdbc:postgresql://dpg-d814e3naqgkc73algps0-a.ohio-postgres.render.com/mapa_db_77ly
spring.datasource.username=mapa_db_77ly_user
spring.datasource.password=G5xUsIdvbNnJr6OjuHzGwZgwIdeqb2qc

# O Spring vai tentar criar as tabelas automaticamente se elas não existirem
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect